# Generated by Django 5.0.4 on 2024-04-08 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user_id', models.CharField(max_length=9)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('last_login_date', models.DateField()),
                ('last_login_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_user_id', models.CharField(max_length=9)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('preferred_store', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('last_login_date', models.DateField()),
                ('last_login_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=4)),
                ('address', models.TextField()),
                ('sunday_open', models.BooleanField()),
                ('monday_open', models.BooleanField()),
                ('tuesday_open', models.BooleanField()),
                ('wednesday_open', models.BooleanField()),
                ('thursday_open', models.BooleanField()),
                ('friday_open', models.BooleanField()),
                ('saturday_open', models.BooleanField()),
                ('sunday_start_time', models.TimeField()),
                ('sunday_end_time', models.TimeField()),
                ('monday_start_time', models.TimeField()),
                ('monday_end_time', models.TimeField()),
                ('tuesday_start_time', models.TimeField()),
                ('tuesday_end_time', models.TimeField()),
                ('wednesday_start_time', models.TimeField()),
                ('wednesday_end_time', models.TimeField()),
                ('thursday_start_time', models.TimeField()),
                ('thursday_end_time', models.TimeField()),
                ('friday_start_time', models.TimeField()),
                ('friday_end_time', models.TimeField()),
                ('saturday_start_time', models.TimeField()),
                ('saturday_end_time', models.TimeField()),
                ('store_phone', models.CharField(max_length=15)),
                ('special_msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store_Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_label', models.CharField(max_length=100)),
                ('discounted_sku', models.IntegerField()),
                ('discounted_category', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=9)),
                ('guest_checkout', models.BooleanField(default=True)),
                ('cart_type', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='saborg.customer_user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('sales_subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sales_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='saborg.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=9)),
                ('short_description', models.CharField(default='product name', max_length=100)),
                ('details', models.TextField(default='product description')),
                ('preferred_vendor', models.CharField(default='no vendor set', max_length=100)),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sku', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='saborg.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_adjustment', models.CharField(max_length=9)),
                ('count_modified_reason', models.CharField()),
                ('qty', models.IntegerField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor', models.CharField(max_length=50)),
                ('adjustment_date', models.DateField()),
                ('adjustment_time', models.TimeField()),
                ('notes', models.TextField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustments', to='saborg.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.CharField(max_length=9)),
                ('qty', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='saborg.cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='saborg.product')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_Inventory_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_inventory_product', models.CharField(max_length=9)),
                ('qty', models.IntegerField()),
                ('uom', models.CharField(max_length=20)),
                ('qty_modified_date', models.DateField()),
                ('qty_modified_time', models.TimeField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inventory_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory_products', to='saborg.inventory_adjustment')),
            ],
        ),
        migrations.CreateModel(
            name='Store_Inventory_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_inventory_product', models.CharField(max_length=9)),
                ('qty', models.IntegerField()),
                ('store_set_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transfer_shipping_enabled', models.BooleanField()),
                ('store_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory_products', to='saborg.store_discount')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory_products', to='saborg.store')),
                ('warehouse_inventory_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inventory_products', to='saborg.warehouse_inventory_product')),
            ],
        ),
    ]
