# Generated by Django 5.0.4 on 2024-04-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saborg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_discount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
