# Generated by Django 5.0.4 on 2024-04-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saborg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='customer_user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inventory_adjustment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.RemoveField(
            model_name='store_discount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='store_inventory_product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='warehouse_inventory_product',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='admin_user_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='cart_item',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer_user',
            name='customer_user_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory_adjustment',
            name='inventory_adjustment',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='store_discount',
            name='discount_label',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='store_inventory_product',
            name='store_inventory_product',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouse_inventory_product',
            name='warehouse_inventory_product',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
