# Generated by Django 5.0.4 on 2024-04-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saborg', '0002_remove_admin_user_id_remove_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
