# Generated by Django 5.0.4 on 2024-04-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saborg', '0002_store_discount_discount_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer_no',
            new_name='customer_user_no',
        ),
    ]
