# Generated by Django 5.0.4 on 2024-04-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saborg', '0003_rename_customer_no_cart_customer_user_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image_url',
            field=models.URLField(default='https://morguefile.nyc3.cdn.digitaloceanspaces.com/imageData/public/files/w/wallyir/preview/fldr_2010_05_06/file7421273138239.jpg'),
        ),
    ]
